PREFIX polis-core: <http://purl.org/polis/ar/core#>
PREFIX polis-graph: <http://purl.org/polis/ar/graph#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX qudt: <http://qudt.org/schema/qudt/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>

SELECT ?partyAcronym ?partyName ?website ?instagramUsername ?twitterUsername
WHERE {
  ?party a polis-core:Party ;
         qudt:acronym ?partyAcronym ;
         foaf:name ?partyName ;
         owl:sameAs ?wd .

  SERVICE <https://query.wikidata.org/sparql> {
    # This is to prevent Fuseki from planning the federated SERVICE as if ?wd were unbound, so Wikidata returned hundreds of thousands of rows
    VALUES ?wikidataParty {
      wd:Q884840
      wd:Q1054298
      wd:Q63645885
      wd:Q46122950
      wd:Q19694667
      wd:Q16947563
      wd:Q2054840
      wd:Q769829
      wd:Q978086
      wd:Q847263
      wd:Q595575
    }
    OPTIONAL { ?wikidataParty wdt:P856 ?website }
    OPTIONAL { ?wikidataParty wdt:P2003 ?instagramUsername }
    OPTIONAL { ?wikidataParty wdt:P2002 ?twitterUsername }
  }
  FILTER (?wd = ?wikidataParty)
}
ORDER BY ?partyAcronym
